sudo: false
addons:
  apt:
    sources:
    # holds gcc 4.9
    - ubuntu-toolchain-r-test
    # holds cmake 3.2.3
    - george-edison55-precise-backports
    # holds boost 1.55
    - boost-latest
    packages:
    - rpmbuild
script:
  - rpmbuild -ba SPECS/libsrtp.spec
